import bootstrap from './bootstrap';
import {
    passThroughHandler,
    pleromaTimelineHandler,
    staticCacheHandler,
} from './fetch-handlers';
import fetchHandlers from './fetch-handlers/fetch-handlers';
import { logger } from './logging';

declare const self: ServiceWorkerGlobalScope;

const log = logger.getLogger('worker');

log.info('Executing worker...');

const WB_MANIFEST = self.__WB_MANIFEST;

// Precache all of the assets generated by your build process.
// Their URLs are injected into the manifest variable below.
// This variable must be present somewhere in your service worker file,
// even if you decide not to use precaching. See https://cra.link/PWA
//precacheAndRoute(WB_MANIFEST);

log.trace(WB_MANIFEST);

fetchHandlers
    .use(staticCacheHandler)
    .use(pleromaTimelineHandler)
    .use(passThroughHandler);

bootstrap();

log.info('Worker executed.');
