name: install
description: install

inputs:
    github_token:
        description: GITHUB_TOKEN
        required: true

runs:
    using: 'composite'
    steps:
        - name: Login to GHCR
          uses: docker/login-action@v2
          with:
              registry: ghcr.io
              username: ${{ github.repository_owner }}
              password: ${{ inputs.github_token }}

        - name: Build athena image
          shell: bash
          run: |
              DOCKER_BUILDKIT=1 docker build \
                --cache-from ghcr.io/samizdapp/athena:${{ github.event.before }} \
                --cache-from ghcr.io/samizdapp/athena:develop \
                --tag ghcr.io/samizdapp/athena:${{ github.sha }} \
                .
              docker push ghcr.io/samizdapp/athena:${{ github.sha }}
        - name: Build and export validate image
          shell: bash
          run: |
              mkdir -p /tmp/images
              docker build . \
                -f .github/workflows/validate.Dockerfile \
                --build-arg VERSION=${{ github.sha }} \
                --tag ghcr.io/samizdapp/athena-validate:${{ github.sha }}
