name: install

description: install
runs:
    using: 'composite'
    steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
              fetch-depth: 0

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: Login to GHCR
          uses: docker/login-action@v2
          with:
              registry: ghcr.io
              username: ${{ github.repository_owner }}
              password: ${{ secrets.GITHUB_TOKEN }}

        - name: Build athena image
          shell: bash
          run: |
              docker buildx build \
                --cache-from type=registry,ref=ghcr.io/samizdapp/athena:${{ github.event.before }} \
                --cache-from type=registry,ref=ghcr.io/samizdapp/athena:develop \
                --tag ghcr.io/samizdapp/athena:${{ github.sha }} \
                --push \
                .
        - name: Build and export validate image
          shell: bash
          run: |
              mkdir -p /tmp/images
              docker build . \
                -f .github/workflows/validate.Dockerfile \
                --build-arg VERSION=${{ github.sha }} \
                --tag ghcr.io/samizdapp/athena-validate:${{ github.sha }}
