name: install
description: install

inputs:
  github_token:
    description: GITHUB_TOKEN
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ inputs.github_token }}

    - name: Build athena image
      shell: bash
      run: |
        docker buildx build \
          --cache-from type=registry,ref=ghcr.io/samizdapp/athena:${{ github.event.before }} \
          --cache-from type=registry,ref=ghcr.io/samizdapp/athena:develop \
          --tag ghcr.io/samizdapp/athena:${{ github.event.pull_request.head.sha }} \
          --push \
          .
    - name: Build and export validate image
      shell: bash
      run: |
        mkdir -p /tmp/images
        docker build . \
          -f .github/workflows/validate.Dockerfile \
          --build-arg VERSION=${{ github.event.pull_request.head.sha }} \
          --tag ghcr.io/samizdapp/athena-validate:${{ github.event.pull_request.head.sha }}
